parser: mineru # options: pymupdf | markitdown | mineru | mineru_vlm
input_dir: "test/"
output_path: "docs/mineru/"  # Directory for individual files
num_workers: 8
allow_network: false
one_file_per_doc: true  # Save each document separately

cleaning:
  unicode_nfkc: true
  fix_hyphenation: true
  remove_headers_footers: true

dedup:
  enabled: true  # Create dedup index (all files are kept)
  fuzzy_threshold: 90

