# MinerU VLM Mode Configuration (Optimized for H200 GPU Cluster)
# Uses MinerU2.5 Vision-Language Model (1.2B parameters)
# GPU HIGHLY RECOMMENDED
# Requirements: pip install 'mineru-vl-utils[transformers]' modelscope pymupdf

parser: mineru_vlm
input_dir: "/data/public_data/arxiv_database/arxiv/pdf/2508"
output_path: "docs/mineru_vlm/"  # Directory for individual parquet files

# ============================================================================
# OPTIMIZED: Increased workers to fully utilize 3 GPU instances
# Each worker processes 1 PDF at a time, distributing load across 3 GPUs
# Recommended: 12-24 workers for 3 GPUs (4-8x GPU count)
# ============================================================================
num_workers: 16  # Increased from 4 to 16 for better GPU utilization

allow_network: true  # May need to download model on first run
one_file_per_doc: true  # Save each document separately

# VLM parser config
parser_config:
  backend: "http"  # or "transformers" / "vllm-engine"
  # Round-robin across multiple HTTP endpoints if provided
  api_urls:
    - "http://172.26.104.1:30100"
    - "http://172.26.104.1:30101"
    - "http://172.26.104.1:30102"
  dpi: 200

  # ============================================================================
  # OPTIMIZED: Batch processing and timeout settings
  # ============================================================================
  batch_size: 32  # Process up to 32 pages per HTTP request (reduce overhead)
  request_timeout: 600  # 10 minutes for large batches
  retry_attempts: 3  # Retry failed requests
  retry_delay: 2  # Seconds between retries


cleaning:
  unicode_nfkc: false  # VLM output is already clean, no cleaning needed
  fix_hyphenation: false
  remove_headers_footers: false

dedup:
  enabled: true  # Create dedup index (all files are kept)
  fuzzy_threshold: 90

