# MinerU VLM Mode Configuration
# Uses MinerU2.5 Vision-Language Model (1.2B parameters)
# GPU HIGHLY RECOMMENDED
# Requirements: pip install 'mineru-vl-utils[transformers]' modelscope pymupdf

parser: mineru_vlm
input_dir: "test/"
output_path: "docs/mineru_vlm/"  # Directory for individual parquet files
num_workers: 1  # VLM mode: use 1 worker to avoid GPU memory issues
allow_network: true  # May need to download model on first run
one_file_per_doc: true  # Save each document separately

cleaning:
  unicode_nfkc: false  # VLM output is already clean, no cleaning needed
  fix_hyphenation: false
  remove_headers_footers: false

dedup:
  enabled: true  # Create dedup index (all files are kept)
  fuzzy_threshold: 90

